# Generated by Django 6.0.2 on 2026-02-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('music', 'Музыка'), ('theatre', 'Театр'), ('art', 'Искусство'), ('sport', 'Спорт'), ('exhibitions', 'Выставки')], max_length=20, verbose_name='Категория')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('venue', models.CharField(max_length=200, verbose_name='Площадка')),
                ('participants', models.CharField(max_length=300, verbose_name='Участники')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(blank=True, help_text='Например: "от 500 ₽" или "бесплатно"', max_length=100, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date'],
            },
        ),
    ]
