# Generated by Django 6.0.3 on 2026-03-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='Сургут, ул. Ленина', max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.CharField(blank=True, help_text='Можно не указывать для выставок', max_length=300, null=True, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, help_text='Базовая цена билета', verbose_name='Цена (в рублях)'),
        ),
    ]
