# Generated by Django 6.0.3 on 2026-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_address_alter_event_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(blank=True, help_text='Для выставок и фестивалей', null=True, verbose_name='Дата окончания'),
        ),
    ]
